local wk = require("which-key")--#.register({
wk.add(
  {
    { "<leader>'", ":Telescope resume<CR>", desc = "Resume last search" },
    { "<leader>,", ":Telescope buffers<CR>", desc = "List buffers" },
    { "<leader>.", ":Telescope file_browser path=%:p:help |select_buffer=true<CR>|", desc = "file explorer" },
    { "<leader><leader>", ":Telescope git_files<CR>", desc = "Project Files" },
    { "<leader>b", group = "Buffers" },
    { "<leader>bK", ":%bd<CR>", desc = "Close all bufers" },
    { "<leader>bN", ":new<BR>", desc = "New buffer" },
    { "<leader>bO", ":%bd|e#<CR>", desc = "Close other buffers" },
    { "<leader>bd", ":bd<CR>", desc = "Close buffer" },
    { "<leader>bk", ":bd<CR>", desc = "Close buffer" },
    { "<leader>c", group = "Code" },
    { "<leader>cd", "<C-]>", desc = "Jump to Definition" },
    { "<leader>g", group = "Git" },
    { "<leader>gB", ":Git blame<CR>", desc = "Blame" },
    { "<leader>gL", ":Git log<CR>", desc = "Log" },
    { "<leader>gg", ":Neogit<CR>", desc = "Git status" },
    { "<leader>o", group = "Application (open)" },
    { "<leader>op", ":NvimTreeToggle<CR>", desc = "Open Tree" },
    { "<leader>p", group = "Project" },
    { "<leader>pf", ":Telescope git_files<CR>", desc = "Find file in Project" },
    { "<leader>pp", ":Telescope project<CR>", desc = "Switch project" },
    { "<leader>r", group = "Rails" },
    { "<leader>rc", ":FindInDir app/controllers<CR>", desc = "find controllers" },
    { "<leader>rm", ":FindInDir app/models<CR>", desc = "find models" },
    { "<leader>rv", ":FindInDir app/views<CR>", desc = "find views" },
    { "<leader>s", group = "Search" },
    { "<leader>sD", ":Telescope dir live_grep<CR>", desc = "Search othe directory" },
    { "<leader>sI", ":TagbarOpenAutoClose<CR>", desc = "Tag bar" },
    { "<leader>sd", ":GrepInCurrentDir<CR>", desc = "Search current dir" },
    { "<leader>si", ":Telescope treesitter<CR>", desc = "Tag bar" },
    { "<leader>sp", ":Telescope live_grep<CR>", desc = "Search project" },
    { "<leader>t", group = "Toggles" },
    { "<leader>tc", ":Telescope colorscheme<CR>", desc = "Toggle colors" },
    { "<leader>tn", ":set number!<CR>", desc = "Toggle number" },
    { "<leader>tr", ":set relativenumber!<CR>", desc = "Toggle relative number" },
    { "<leader>tw", ":set wrap!<CR>", desc = "Toggle wrap" },
    { "<leader>w", group = "Window" },
    { "<leader>wh", "<C-h>", desc = "Move left " },
    { "<leader>wj", "<C-j>", desc = "Move down " },
    { "<leader>wk", "<C-k>", desc = "Move up " },
    { "<leader>wl", "<C-l>", desc = "Move right " },
    { "<leader>wmm", "<C-w>T", desc = "Maximize" },
    { "<leader>wq", ":close<CR>", desc = "Close window" },
    { "<leader>ws", ":split<CR>", desc = "Horizonal Split" },
    { "<leader>wv", ":vsplit<CR>", desc = "Vertical Split" },
    {"<leader>l", group = "LLM" },
    {"<leader>lg", ":Gen<CR>", desc = "Gen Menu" },
    {"<leader>lu", ":Gen Unit_Test<CR>", desc = "Gen Unit test for selection" },
    {"<leader>ls", ":Gen System_Test<CR>", desc = "Gen System test for selection" },
    {"<leader>lf", ":Gen Feature_Spec<CR>", desc = "Gen Feature Spec for selection" },
    {"<leader>lm", ":Gen Unit_Spec<CR>", desc = "Gen Unit Spec for selection" },
  })
--  ["<leader>"] = {
--    ["."] = { ":Telescope file_browser path=%:p:h select_buffer=true<CR>", "file explorer" },
--    [","] = { ":Telescope buffers<CR>", "List buffers" },
--    ["'"] = { ":Telescope resume<CR>", "Resume last search" },
--    ["<leader>"] = { ":Telescope git_files<CR>", "Project Files" },
--    b = {
--      name = "Buffers",
--      k = { ":bd<CR>", "Close buffer" },
--      d = { ":bd<CR>", "Close buffer" },
--      K = { ":%bd<CR>", "Close all bufers" },
--      O = { ":%bd|e#<CR>", "Close other buffers" },
--      N = { ":new<BR>", "New buffer" },
--    },
--    c = {
--      name = "Code",
--      d = { "<C-]>", "Jump to Definition" },
--    },
--    g = {
--      name = "Git",
--      g = { ":Neogit<CR>", "Git status" },
--      B = { ":Git blame<CR>", "Blame" },
--      L = { ":Git log<CR>", "Log" },
--    },
--    o = {
--      name = "Application (open)",
--      p = { ":NvimTreeToggle<CR>", "Open Tree" },
--    },
--    p = {
--      name = "Project",
--      p = { ":Telescope project<CR>", "Switch project" },
--      f = { ":Telescope git_files<CR>", "Find file in Project" },
--    },
--    s = {
--      name = "Search",
--      d = { ":GrepInCurrentDir<CR>", "Search current dir" },
--      p = { ":Telescope live_grep<CR>", "Search project" },
--      D = { ":Telescope dir live_grep<CR>", "Search othe directory" },
--      i = { ":Telescope treesitter<CR>", "Tag bar"},
--      I = { ":TagbarOpenAutoClose<CR>", "Tag bar"},
--    },
--    w = {
--      name = "Window",
--      v = { ":vsplit<CR>", "Vertical Split"},
--      s = { ":split<CR>", "Horizonal Split"},
--      q = { ":close<CR>", "Close window"},
--      h = { "<C-h>", "Move left "},
--      l = { "<C-l>", "Move right "},
--      j = { "<C-j>", "Move down "},
--      k = { "<C-k>", "Move up "},
--      m = {
--        m = { "<C-w>T", "Maximize" }
--      }
--    },
--    r = {
--      name = "Rails",
--      c = { ":FindInDir app/controllers<CR>", "find controllers" },
--      v = { ":FindInDir app/views<CR>", "find views" },
--      m = { ":FindInDir app/models<CR>", "find models" },
--    },
--    t = {
--      name = "Toggles",
--      w = { ":set wrap!<CR>", "Toggle wrap" },
--      r = { ":set relativenumber!<CR>", "Toggle relative number" },
--      n = { ":set number!<CR>", "Toggle number" },
--      c = { ":Telescope colorscheme<CR>", "Toggle colors" },
--    }
--  }
--})
